-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Hasura.Object exposing (..)


type Projects
    = Projects


type Projects_aggregate
    = Projects_aggregate


type Projects_aggregate_fields
    = Projects_aggregate_fields


type Projects_avg_fields
    = Projects_avg_fields


type Projects_max_fields
    = Projects_max_fields


type Projects_min_fields
    = Projects_min_fields


type Projects_mutation_response
    = Projects_mutation_response


type Projects_stddev_fields
    = Projects_stddev_fields


type Projects_stddev_pop_fields
    = Projects_stddev_pop_fields


type Projects_stddev_samp_fields
    = Projects_stddev_samp_fields


type Projects_sum_fields
    = Projects_sum_fields


type Projects_var_pop_fields
    = Projects_var_pop_fields


type Projects_var_samp_fields
    = Projects_var_samp_fields


type Projects_variance_fields
    = Projects_variance_fields
